# Generated by Django 4.2.8 on 2025-06-09 03:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tunaapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SongGenre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='song_genres', to='tunaapi.genre')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='song_genres', to='tunaapi.song')),
            ],
            options={
                'unique_together': {('song', 'genre')},
            },
        ),
    ]
